// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: user.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_HandleRegister_FullMethodName                = "/UserService/HandleRegister"
	UserService_HandleGenerateOneTimePassword_FullMethodName = "/UserService/HandleGenerateOneTimePassword"
	UserService_HandleLogin_FullMethodName                   = "/UserService/HandleLogin"
	UserService_HandleVerifyOneTimePassword_FullMethodName   = "/UserService/HandleVerifyOneTimePassword"
	UserService_HandleGoogleAuthentication_FullMethodName    = "/UserService/HandleGoogleAuthentication"
	UserService_HandleGoogleCallback_FullMethodName          = "/UserService/HandleGoogleCallback"
	UserService_FindByIdentifier_FullMethodName              = "/UserService/FindByIdentifier"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	HandleRegister(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CommandUserResponse, error)
	HandleGenerateOneTimePassword(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleLogin(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*PayloadResponse, error)
	HandleVerifyOneTimePassword(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*QueryUserResponse, error)
	HandleGoogleAuthentication(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PayloadResponse, error)
	HandleGoogleCallback(ctx context.Context, in *GoogleCallbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FindByIdentifier(ctx context.Context, in *UserIdentifier, opts ...grpc.CallOption) (*QueryUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) HandleRegister(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CommandUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandUserResponse)
	err := c.cc.Invoke(ctx, UserService_HandleRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleGenerateOneTimePassword(ctx context.Context, in *GenerateOtpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_HandleGenerateOneTimePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleLogin(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*PayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayloadResponse)
	err := c.cc.Invoke(ctx, UserService_HandleLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleVerifyOneTimePassword(ctx context.Context, in *VerifyOtpRequest, opts ...grpc.CallOption) (*QueryUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserResponse)
	err := c.cc.Invoke(ctx, UserService_HandleVerifyOneTimePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleGoogleAuthentication(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayloadResponse)
	err := c.cc.Invoke(ctx, UserService_HandleGoogleAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HandleGoogleCallback(ctx context.Context, in *GoogleCallbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UserService_HandleGoogleCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindByIdentifier(ctx context.Context, in *UserIdentifier, opts ...grpc.CallOption) (*QueryUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserResponse)
	err := c.cc.Invoke(ctx, UserService_FindByIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	HandleRegister(context.Context, *CreateUserRequest) (*CommandUserResponse, error)
	HandleGenerateOneTimePassword(context.Context, *GenerateOtpRequest) (*emptypb.Empty, error)
	HandleLogin(context.Context, *LoginUserRequest) (*PayloadResponse, error)
	HandleVerifyOneTimePassword(context.Context, *VerifyOtpRequest) (*QueryUserResponse, error)
	HandleGoogleAuthentication(context.Context, *emptypb.Empty) (*PayloadResponse, error)
	HandleGoogleCallback(context.Context, *GoogleCallbackRequest) (*emptypb.Empty, error)
	FindByIdentifier(context.Context, *UserIdentifier) (*QueryUserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) HandleRegister(context.Context, *CreateUserRequest) (*CommandUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRegister not implemented")
}
func (UnimplementedUserServiceServer) HandleGenerateOneTimePassword(context.Context, *GenerateOtpRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGenerateOneTimePassword not implemented")
}
func (UnimplementedUserServiceServer) HandleLogin(context.Context, *LoginUserRequest) (*PayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleLogin not implemented")
}
func (UnimplementedUserServiceServer) HandleVerifyOneTimePassword(context.Context, *VerifyOtpRequest) (*QueryUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleVerifyOneTimePassword not implemented")
}
func (UnimplementedUserServiceServer) HandleGoogleAuthentication(context.Context, *emptypb.Empty) (*PayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGoogleAuthentication not implemented")
}
func (UnimplementedUserServiceServer) HandleGoogleCallback(context.Context, *GoogleCallbackRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGoogleCallback not implemented")
}
func (UnimplementedUserServiceServer) FindByIdentifier(context.Context, *UserIdentifier) (*QueryUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByIdentifier not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_HandleRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleRegister(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleGenerateOneTimePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleGenerateOneTimePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleGenerateOneTimePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleGenerateOneTimePassword(ctx, req.(*GenerateOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleLogin(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleVerifyOneTimePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleVerifyOneTimePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleVerifyOneTimePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleVerifyOneTimePassword(ctx, req.(*VerifyOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleGoogleAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleGoogleAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleGoogleAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleGoogleAuthentication(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HandleGoogleCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HandleGoogleCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HandleGoogleCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HandleGoogleCallback(ctx, req.(*GoogleCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindByIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindByIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_FindByIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindByIdentifier(ctx, req.(*UserIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRegister",
			Handler:    _UserService_HandleRegister_Handler,
		},
		{
			MethodName: "HandleGenerateOneTimePassword",
			Handler:    _UserService_HandleGenerateOneTimePassword_Handler,
		},
		{
			MethodName: "HandleLogin",
			Handler:    _UserService_HandleLogin_Handler,
		},
		{
			MethodName: "HandleVerifyOneTimePassword",
			Handler:    _UserService_HandleVerifyOneTimePassword_Handler,
		},
		{
			MethodName: "HandleGoogleAuthentication",
			Handler:    _UserService_HandleGoogleAuthentication_Handler,
		},
		{
			MethodName: "HandleGoogleCallback",
			Handler:    _UserService_HandleGoogleCallback_Handler,
		},
		{
			MethodName: "FindByIdentifier",
			Handler:    _UserService_FindByIdentifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
