// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,3,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type GenerateOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOtpRequest) Reset() {
	*x = GenerateOtpRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOtpRequest) ProtoMessage() {}

func (x *GenerateOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOtpRequest.ProtoReflect.Descriptor instead.
func (*GenerateOtpRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateOtpRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type JwtClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtClaimResponse) Reset() {
	*x = JwtClaimResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtClaimResponse) ProtoMessage() {}

func (x *JwtClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtClaimResponse.ProtoReflect.Descriptor instead.
func (*JwtClaimResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *JwtClaimResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JwtClaimResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type LoginUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserIdentifier string                 `protobuf:"bytes,1,opt,name=UserIdentifier,proto3" json:"UserIdentifier,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserRequest) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyOtpRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Email                string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	OneTimePasswordToken string                 `protobuf:"bytes,2,opt,name=OneTimePasswordToken,proto3" json:"OneTimePasswordToken,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifyOtpRequest) Reset() {
	*x = VerifyOtpRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOtpRequest) ProtoMessage() {}

func (x *VerifyOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyOtpRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyOtpRequest) GetOneTimePasswordToken() string {
	if x != nil {
		return x.OneTimePasswordToken
	}
	return ""
}

type GoogleCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenState    string                 `protobuf:"bytes,1,opt,name=tokenState,proto3" json:"tokenState,omitempty"`
	QueryCode     string                 `protobuf:"bytes,2,opt,name=queryCode,proto3" json:"queryCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCallbackRequest) Reset() {
	*x = GoogleCallbackRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCallbackRequest) ProtoMessage() {}

func (x *GoogleCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCallbackRequest.ProtoReflect.Descriptor instead.
func (*GoogleCallbackRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleCallbackRequest) GetTokenState() string {
	if x != nil {
		return x.TokenState
	}
	return ""
}

func (x *GoogleCallbackRequest) GetQueryCode() string {
	if x != nil {
		return x.QueryCode
	}
	return ""
}

type UserJwtClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=Email,proto3,oneof" json:"Email,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,2,opt,name=PhoneNumber,proto3,oneof" json:"PhoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJwtClaim) Reset() {
	*x = UserJwtClaim{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJwtClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJwtClaim) ProtoMessage() {}

func (x *UserJwtClaim) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJwtClaim.ProtoReflect.Descriptor instead.
func (*UserJwtClaim) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserJwtClaim) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserJwtClaim) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

type CommandUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandUserResponse) Reset() {
	*x = CommandUserResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandUserResponse) ProtoMessage() {}

func (x *CommandUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandUserResponse.ProtoReflect.Descriptor instead.
func (*CommandUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *CommandUserResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type QueryUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Role            string                 `protobuf:"bytes,5,opt,name=Role,proto3" json:"Role,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,6,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ProfilePicture  string                 `protobuf:"bytes,7,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	IsActive        bool                   `protobuf:"varint,8,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,10,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	EmailVerifiedAt string                 `protobuf:"bytes,11,opt,name=EmailVerifiedAt,proto3" json:"EmailVerifiedAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryUserResponse) Reset() {
	*x = QueryUserResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserResponse) ProtoMessage() {}

func (x *QueryUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserResponse.ProtoReflect.Descriptor instead.
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUserResponse) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *QueryUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *QueryUserResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *QueryUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *QueryUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *QueryUserResponse) GetProfilePicture() string {
	if x != nil {
		return x.ProfilePicture
	}
	return ""
}

func (x *QueryUserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *QueryUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryUserResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *QueryUserResponse) GetEmailVerifiedAt() string {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return ""
}

type PayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadResponse) Reset() {
	*x = PayloadResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadResponse) ProtoMessage() {}

func (x *PayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadResponse.ProtoReflect.Descriptor instead.
func (*PayloadResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *PayloadResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type UserIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentifier) Reset() {
	*x = UserIdentifier{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentifier) ProtoMessage() {}

func (x *UserIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentifier.ProtoReflect.Descriptor instead.
func (*UserIdentifier) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserIdentifier) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIdentifier) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa5\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12 \n" +
	"\vPhoneNumber\x18\x03 \x01(\tR\vPhoneNumber\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12(\n" +
	"\x0fConfirmPassword\x18\x05 \x01(\tR\x0fConfirmPassword\"B\n" +
	"\x12GenerateOtpRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\"J\n" +
	"\x10JwtClaimResponse\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12 \n" +
	"\vPhoneNumber\x18\x02 \x01(\tR\vPhoneNumber\"V\n" +
	"\x10LoginUserRequest\x12&\n" +
	"\x0eUserIdentifier\x18\x01 \x01(\tR\x0eUserIdentifier\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\\\n" +
	"\x10VerifyOtpRequest\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x122\n" +
	"\x14OneTimePasswordToken\x18\x02 \x01(\tR\x14OneTimePasswordToken\"U\n" +
	"\x15GoogleCallbackRequest\x12\x1e\n" +
	"\n" +
	"tokenState\x18\x01 \x01(\tR\n" +
	"tokenState\x12\x1c\n" +
	"\tqueryCode\x18\x02 \x01(\tR\tqueryCode\"j\n" +
	"\fUserJwtClaim\x12\x19\n" +
	"\x05Email\x18\x01 \x01(\tH\x00R\x05Email\x88\x01\x01\x12%\n" +
	"\vPhoneNumber\x18\x02 \x01(\tH\x01R\vPhoneNumber\x88\x01\x01B\b\n" +
	"\x06_EmailB\x0e\n" +
	"\f_PhoneNumber\"3\n" +
	"\x13CommandUserResponse\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\"\xc9\x02\n" +
	"\x11QueryUserResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x12\n" +
	"\x04Role\x18\x05 \x01(\tR\x04Role\x12 \n" +
	"\vPhoneNumber\x18\x06 \x01(\tR\vPhoneNumber\x12&\n" +
	"\x0eProfilePicture\x18\a \x01(\tR\x0eProfilePicture\x12\x1a\n" +
	"\bIsActive\x18\b \x01(\bR\bIsActive\x12\x1c\n" +
	"\tCreatedAt\x18\t \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\n" +
	" \x01(\tR\tUpdatedAt\x12(\n" +
	"\x0fEmailVerifiedAt\x18\v \x01(\tR\x0fEmailVerifiedAt\"+\n" +
	"\x0fPayloadResponse\x12\x18\n" +
	"\aPayload\x18\x01 \x01(\tR\aPayload\"H\n" +
	"\x0eUserIdentifier\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12 \n" +
	"\vPhoneNumber\x18\x02 \x01(\tR\vPhoneNumber2\xda\x03\n" +
	"\vUserService\x12:\n" +
	"\x0eHandleRegister\x12\x12.CreateUserRequest\x1a\x14.CommandUserResponse\x12L\n" +
	"\x1dHandleGenerateOneTimePassword\x12\x13.GenerateOtpRequest\x1a\x16.google.protobuf.Empty\x122\n" +
	"\vHandleLogin\x12\x11.LoginUserRequest\x1a\x10.PayloadResponse\x12D\n" +
	"\x1bHandleVerifyOneTimePassword\x12\x11.VerifyOtpRequest\x1a\x12.QueryUserResponse\x12F\n" +
	"\x1aHandleGoogleAuthentication\x12\x16.google.protobuf.Empty\x1a\x10.PayloadResponse\x12F\n" +
	"\x14HandleGoogleCallback\x12\x16.GoogleCallbackRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x10FindByIdentifier\x12\x0f.UserIdentifier\x1a\x12.QueryUserResponseBDZBgithub.com/alfarezyyd/go-tokopaedi-microservices/protobuf/genprotob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),     // 0: CreateUserRequest
	(*GenerateOtpRequest)(nil),    // 1: GenerateOtpRequest
	(*JwtClaimResponse)(nil),      // 2: JwtClaimResponse
	(*LoginUserRequest)(nil),      // 3: LoginUserRequest
	(*VerifyOtpRequest)(nil),      // 4: VerifyOtpRequest
	(*GoogleCallbackRequest)(nil), // 5: GoogleCallbackRequest
	(*UserJwtClaim)(nil),          // 6: UserJwtClaim
	(*CommandUserResponse)(nil),   // 7: CommandUserResponse
	(*QueryUserResponse)(nil),     // 8: QueryUserResponse
	(*PayloadResponse)(nil),       // 9: PayloadResponse
	(*UserIdentifier)(nil),        // 10: UserIdentifier
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: UserService.HandleRegister:input_type -> CreateUserRequest
	1,  // 1: UserService.HandleGenerateOneTimePassword:input_type -> GenerateOtpRequest
	3,  // 2: UserService.HandleLogin:input_type -> LoginUserRequest
	4,  // 3: UserService.HandleVerifyOneTimePassword:input_type -> VerifyOtpRequest
	11, // 4: UserService.HandleGoogleAuthentication:input_type -> google.protobuf.Empty
	5,  // 5: UserService.HandleGoogleCallback:input_type -> GoogleCallbackRequest
	10, // 6: UserService.FindByIdentifier:input_type -> UserIdentifier
	7,  // 7: UserService.HandleRegister:output_type -> CommandUserResponse
	11, // 8: UserService.HandleGenerateOneTimePassword:output_type -> google.protobuf.Empty
	9,  // 9: UserService.HandleLogin:output_type -> PayloadResponse
	8,  // 10: UserService.HandleVerifyOneTimePassword:output_type -> QueryUserResponse
	9,  // 11: UserService.HandleGoogleAuthentication:output_type -> PayloadResponse
	11, // 12: UserService.HandleGoogleCallback:output_type -> google.protobuf.Empty
	8,  // 13: UserService.FindByIdentifier:output_type -> QueryUserResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
